// Code generated by protoc-gen-go.
// source: user.proto
// DO NOT EDIT!

package login

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type AccountType int32

const (
	AccountType_kSelf    AccountType = 0
	AccountType_kSina    AccountType = 1
	AccountType_kTencent AccountType = 2
	AccountType_kBaidu   AccountType = 3
	AccountType_kRenren  AccountType = 4
	AccountType_kTaobao  AccountType = 5
	AccountType_kMomo    AccountType = 6
	AccountType_kDouban  AccountType = 7
	AccountType_kWechat  AccountType = 8
	AccountType_kEnd     AccountType = 9
)

var AccountType_name = map[int32]string{
	0: "kSelf",
	1: "kSina",
	2: "kTencent",
	3: "kBaidu",
	4: "kRenren",
	5: "kTaobao",
	6: "kMomo",
	7: "kDouban",
	8: "kWechat",
	9: "kEnd",
}
var AccountType_value = map[string]int32{
	"kSelf":    0,
	"kSina":    1,
	"kTencent": 2,
	"kBaidu":   3,
	"kRenren":  4,
	"kTaobao":  5,
	"kMomo":    6,
	"kDouban":  7,
	"kWechat":  8,
	"kEnd":     9,
}

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}
func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}
func (x *AccountType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AccountType_value, data, "AccountType")
	if err != nil {
		return err
	}
	*x = AccountType(value)
	return nil
}

type Birthday_Month int32

const (
	Birthday_kNone      Birthday_Month = 0
	Birthday_kJanuary   Birthday_Month = 1
	Birthday_kFebruary  Birthday_Month = 2
	Birthday_kMarch     Birthday_Month = 3
	Birthday_kApril     Birthday_Month = 4
	Birthday_kMay       Birthday_Month = 5
	Birthday_kJune      Birthday_Month = 6
	Birthday_kJuly      Birthday_Month = 7
	Birthday_kAugust    Birthday_Month = 8
	Birthday_kSeptember Birthday_Month = 9
	Birthday_kOctober   Birthday_Month = 10
	Birthday_kNovember  Birthday_Month = 11
	Birthday_kDecember  Birthday_Month = 12
	Birthday_kEnd       Birthday_Month = 13
)

var Birthday_Month_name = map[int32]string{
	0:  "kNone",
	1:  "kJanuary",
	2:  "kFebruary",
	3:  "kMarch",
	4:  "kApril",
	5:  "kMay",
	6:  "kJune",
	7:  "kJuly",
	8:  "kAugust",
	9:  "kSeptember",
	10: "kOctober",
	11: "kNovember",
	12: "kDecember",
	13: "kEnd",
}
var Birthday_Month_value = map[string]int32{
	"kNone":      0,
	"kJanuary":   1,
	"kFebruary":  2,
	"kMarch":     3,
	"kApril":     4,
	"kMay":       5,
	"kJune":      6,
	"kJuly":      7,
	"kAugust":    8,
	"kSeptember": 9,
	"kOctober":   10,
	"kNovember":  11,
	"kDecember":  12,
	"kEnd":       13,
}

func (x Birthday_Month) Enum() *Birthday_Month {
	p := new(Birthday_Month)
	*p = x
	return p
}
func (x Birthday_Month) String() string {
	return proto.EnumName(Birthday_Month_name, int32(x))
}
func (x *Birthday_Month) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Birthday_Month_value, data, "Birthday_Month")
	if err != nil {
		return err
	}
	*x = Birthday_Month(value)
	return nil
}

type Profile_Gender int32

const (
	Profile_PRIVATE Profile_Gender = 0
	Profile_MALE    Profile_Gender = 1
	Profile_FEMALE  Profile_Gender = 2
	Profile_BL      Profile_Gender = 3
	Profile_GL      Profile_Gender = 4
	Profile_BLG     Profile_Gender = 5
	Profile_GLB     Profile_Gender = 6
)

var Profile_Gender_name = map[int32]string{
	0: "PRIVATE",
	1: "MALE",
	2: "FEMALE",
	3: "BL",
	4: "GL",
	5: "BLG",
	6: "GLB",
}
var Profile_Gender_value = map[string]int32{
	"PRIVATE": 0,
	"MALE":    1,
	"FEMALE":  2,
	"BL":      3,
	"GL":      4,
	"BLG":     5,
	"GLB":     6,
}

func (x Profile_Gender) Enum() *Profile_Gender {
	p := new(Profile_Gender)
	*p = x
	return p
}
func (x Profile_Gender) String() string {
	return proto.EnumName(Profile_Gender_name, int32(x))
}
func (x *Profile_Gender) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Profile_Gender_value, data, "Profile_Gender")
	if err != nil {
		return err
	}
	*x = Profile_Gender(value)
	return nil
}

type Request_Command int32

const (
	Request_kPing     Request_Command = 0
	Request_kRegister Request_Command = 1
	Request_kLogin    Request_Command = 2
	Request_kEnd      Request_Command = 3
)

var Request_Command_name = map[int32]string{
	0: "kPing",
	1: "kRegister",
	2: "kLogin",
	3: "kEnd",
}
var Request_Command_value = map[string]int32{
	"kPing":     0,
	"kRegister": 1,
	"kLogin":    2,
	"kEnd":      3,
}

func (x Request_Command) Enum() *Request_Command {
	p := new(Request_Command)
	*p = x
	return p
}
func (x Request_Command) String() string {
	return proto.EnumName(Request_Command_name, int32(x))
}
func (x *Request_Command) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Request_Command_value, data, "Request_Command")
	if err != nil {
		return err
	}
	*x = Request_Command(value)
	return nil
}

type Response_Status int32

const (
	Response_kOk     Response_Status = 0
	Response_kError  Response_Status = 1
	Response_kOthers Response_Status = 2
)

var Response_Status_name = map[int32]string{
	0: "kOk",
	1: "kError",
	2: "kOthers",
}
var Response_Status_value = map[string]int32{
	"kOk":     0,
	"kError":  1,
	"kOthers": 2,
}

func (x Response_Status) Enum() *Response_Status {
	p := new(Response_Status)
	*p = x
	return p
}
func (x Response_Status) String() string {
	return proto.EnumName(Response_Status_name, int32(x))
}
func (x *Response_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Response_Status_value, data, "Response_Status")
	if err != nil {
		return err
	}
	*x = Response_Status(value)
	return nil
}

type Account struct {
	Type             *AccountType `protobuf:"varint,1,req,name=type,enum=login.AccountType,def=0" json:"type,omitempty"`
	Name             *string      `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Token            *string      `protobuf:"bytes,3,req,name=token" json:"token,omitempty"`
	Email            *string      `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}

const Default_Account_Type AccountType = AccountType_kSelf

func (m *Account) GetType() AccountType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_Account_Type
}

func (m *Account) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Account) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

type Friend struct {
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Friend) Reset()         { *m = Friend{} }
func (m *Friend) String() string { return proto.CompactTextString(m) }
func (*Friend) ProtoMessage()    {}

func (m *Friend) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type Birthday struct {
	Year             *int32          `protobuf:"fixed32,1,req,name=year,def=1970" json:"year,omitempty"`
	Month            *Birthday_Month `protobuf:"varint,2,req,name=month,enum=login.Birthday_Month,def=1" json:"month,omitempty"`
	Day              *int32          `protobuf:"fixed32,3,req,name=day,def=1" json:"day,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Birthday) Reset()         { *m = Birthday{} }
func (m *Birthday) String() string { return proto.CompactTextString(m) }
func (*Birthday) ProtoMessage()    {}

const Default_Birthday_Year int32 = 1970
const Default_Birthday_Month Birthday_Month = Birthday_kJanuary
const Default_Birthday_Day int32 = 1

func (m *Birthday) GetYear() int32 {
	if m != nil && m.Year != nil {
		return *m.Year
	}
	return Default_Birthday_Year
}

func (m *Birthday) GetMonth() Birthday_Month {
	if m != nil && m.Month != nil {
		return *m.Month
	}
	return Default_Birthday_Month
}

func (m *Birthday) GetDay() int32 {
	if m != nil && m.Day != nil {
		return *m.Day
	}
	return Default_Birthday_Day
}

type Profile struct {
	Gender           *Profile_Gender `protobuf:"varint,1,opt,name=gender,enum=login.Profile_Gender,def=0" json:"gender,omitempty"`
	Birthday         *Birthday       `protobuf:"bytes,2,opt,name=birthday" json:"birthday,omitempty"`
	Emails           []string        `protobuf:"bytes,3,rep,name=emails" json:"emails,omitempty"`
	Friends          []*Friend       `protobuf:"bytes,4,rep,name=friends" json:"friends,omitempty"`
	Accounts         []*Account      `protobuf:"bytes,5,rep,name=accounts" json:"accounts,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}

const Default_Profile_Gender Profile_Gender = Profile_PRIVATE

func (m *Profile) GetGender() Profile_Gender {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return Default_Profile_Gender
}

func (m *Profile) GetBirthday() *Birthday {
	if m != nil {
		return m.Birthday
	}
	return nil
}

func (m *Profile) GetEmails() []string {
	if m != nil {
		return m.Emails
	}
	return nil
}

func (m *Profile) GetFriends() []*Friend {
	if m != nil {
		return m.Friends
	}
	return nil
}

func (m *Profile) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type User struct {
	Account          []*Account `protobuf:"bytes,1,rep,name=account" json:"account,omitempty"`
	Profile          *Profile   `protobuf:"bytes,2,opt,name=profile" json:"profile,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}

func (m *User) GetAccount() []*Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *User) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type Request struct {
	Command          *Request_Command `protobuf:"varint,1,req,name=command,enum=login.Request_Command,def=0" json:"command,omitempty"`
	Register         *User            `protobuf:"bytes,2,opt,name=register" json:"register,omitempty"`
	Login            *Account         `protobuf:"bytes,3,opt,name=login" json:"login,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

const Default_Request_Command Request_Command = Request_kPing

func (m *Request) GetCommand() Request_Command {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return Default_Request_Command
}

func (m *Request) GetRegister() *User {
	if m != nil {
		return m.Register
	}
	return nil
}

func (m *Request) GetLogin() *Account {
	if m != nil {
		return m.Login
	}
	return nil
}

type Response struct {
	Status           *Response_Status `protobuf:"varint,1,req,name=status,enum=login.Response_Status" json:"status,omitempty"`
	Error            *string          `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	Pong             *string          `protobuf:"bytes,3,opt,name=pong" json:"pong,omitempty"`
	User             *User            `protobuf:"bytes,4,opt,name=user" json:"user,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

func (m *Response) GetStatus() Response_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Response_kOk
}

func (m *Response) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *Response) GetPong() string {
	if m != nil && m.Pong != nil {
		return *m.Pong
	}
	return ""
}

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterEnum("login.AccountType", AccountType_name, AccountType_value)
	proto.RegisterEnum("login.Birthday_Month", Birthday_Month_name, Birthday_Month_value)
	proto.RegisterEnum("login.Profile_Gender", Profile_Gender_name, Profile_Gender_value)
	proto.RegisterEnum("login.Request_Command", Request_Command_name, Request_Command_value)
	proto.RegisterEnum("login.Response_Status", Response_Status_name, Response_Status_value)
}
