// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

package message

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Request_Command int32

const (
	Request_kPing     Request_Command = 0
	Request_kVeryfy   Request_Command = 1
	Request_kRegister Request_Command = 2
	Request_kLogin    Request_Command = 3
	Request_kUpdate   Request_Command = 4
	Request_kEnd      Request_Command = 5
)

var Request_Command_name = map[int32]string{
	0: "kPing",
	1: "kVeryfy",
	2: "kRegister",
	3: "kLogin",
	4: "kUpdate",
	5: "kEnd",
}
var Request_Command_value = map[string]int32{
	"kPing":     0,
	"kVeryfy":   1,
	"kRegister": 2,
	"kLogin":    3,
	"kUpdate":   4,
	"kEnd":      5,
}

func (x Request_Command) Enum() *Request_Command {
	p := new(Request_Command)
	*p = x
	return p
}
func (x Request_Command) String() string {
	return proto.EnumName(Request_Command_name, int32(x))
}
func (x *Request_Command) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Request_Command_value, data, "Request_Command")
	if err != nil {
		return err
	}
	*x = Request_Command(value)
	return nil
}

type Response_Status int32

const (
	Response_kOk    Response_Status = 0
	Response_kError Response_Status = 1
	Response_kEnd   Response_Status = 2
)

var Response_Status_name = map[int32]string{
	0: "kOk",
	1: "kError",
	2: "kEnd",
}
var Response_Status_value = map[string]int32{
	"kOk":    0,
	"kError": 1,
	"kEnd":   2,
}

func (x Response_Status) Enum() *Response_Status {
	p := new(Response_Status)
	*p = x
	return p
}
func (x Response_Status) String() string {
	return proto.EnumName(Response_Status_name, int32(x))
}
func (x *Response_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Response_Status_value, data, "Response_Status")
	if err != nil {
		return err
	}
	*x = Response_Status(value)
	return nil
}

type Request struct {
	Type             *uint32                   `protobuf:"varint,1,req,name=type,def=0" json:"type,omitempty"`
	Command          *Request_Command          `protobuf:"varint,2,req,name=command,enum=message.Request_Command,def=0" json:"command,omitempty"`
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}

var extRange_Request = []proto.ExtensionRange{
	{8, 128},
}

func (*Request) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Request
}
func (m *Request) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

const Default_Request_Type uint32 = 0
const Default_Request_Command Request_Command = Request_kPing

func (m *Request) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_Request_Type
}

func (m *Request) GetCommand() Request_Command {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return Default_Request_Command
}

type Response struct {
	Type             *uint32                   `protobuf:"varint,1,req,name=type,def=0" json:"type,omitempty"`
	Status           *Response_Status          `protobuf:"varint,2,req,name=status,enum=message.Response_Status,def=0" json:"status,omitempty"`
	Error            *string                   `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}

var extRange_Response = []proto.ExtensionRange{
	{8, 128},
}

func (*Response) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_Response
}
func (m *Response) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

const Default_Response_Type uint32 = 0
const Default_Response_Status Response_Status = Response_kOk

func (m *Response) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Default_Response_Type
}

func (m *Response) GetStatus() Response_Status {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Default_Response_Status
}

func (m *Response) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("message.Request_Command", Request_Command_name, Request_Command_value)
	proto.RegisterEnum("message.Response_Status", Response_Status_name, Response_Status_value)
}
